# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/QLearning.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol/QLearning.proto',
  package='aimaker.predictor.qlearning',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x18protocol/QLearning.proto\x12\x1b\x61imaker.predictor.qlearning\"\xb3\x01\n\nActionInfo\x12<\n\x0b\x61\x63tion_type\x18\x01 \x01(\x0e\x32\'.aimaker.predictor.qlearning.ActionType\x12\x18\n\x10template_pos_cnt\x18\x02 \x01(\x05\x12\x15\n\ritem_type_cnt\x18\x03 \x01(\x05\x12\x12\n\nitem_types\x18\x04 \x03(\x05\x12\x0e\n\x06values\x18\x05 \x03(\x02\x12\x12\n\nscore_type\x18\x06 \x01(\x05\":\n\x0bTableRecord\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\x05\x12\x0e\n\x06reward\x18\x03 \x01(\x02\"\x9d\x01\n\x0eQlearningModel\x12\x14\n\x0c\x65xplore_prob\x18\x01 \x01(\x02\x12<\n\x0b\x61\x63tion_info\x18\x02 \x01(\x0b\x32\'.aimaker.predictor.qlearning.ActionInfo\x12\x37\n\x05table\x18\x03 \x03(\x0b\x32(.aimaker.predictor.qlearning.TableRecord*I\n\nActionType\x12\x12\n\x0e\x41\x43TION_UNKNOWN\x10\x00\x12\x13\n\x0f\x41\x43TION_TEMPLATE\x10\x01\x12\x12\n\x0e\x41\x43TION_NUMERIC\x10\x02\x62\x06proto3'
)

_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='aimaker.predictor.qlearning.ActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTION_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_TEMPLATE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_NUMERIC', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=459,
  serialized_end=532,
)
_sym_db.RegisterEnumDescriptor(_ACTIONTYPE)

ActionType = enum_type_wrapper.EnumTypeWrapper(_ACTIONTYPE)
ACTION_UNKNOWN = 0
ACTION_TEMPLATE = 1
ACTION_NUMERIC = 2



_ACTIONINFO = _descriptor.Descriptor(
  name='ActionInfo',
  full_name='aimaker.predictor.qlearning.ActionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_type', full_name='aimaker.predictor.qlearning.ActionInfo.action_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='template_pos_cnt', full_name='aimaker.predictor.qlearning.ActionInfo.template_pos_cnt', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_type_cnt', full_name='aimaker.predictor.qlearning.ActionInfo.item_type_cnt', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_types', full_name='aimaker.predictor.qlearning.ActionInfo.item_types', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='aimaker.predictor.qlearning.ActionInfo.values', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score_type', full_name='aimaker.predictor.qlearning.ActionInfo.score_type', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=237,
)


_TABLERECORD = _descriptor.Descriptor(
  name='TableRecord',
  full_name='aimaker.predictor.qlearning.TableRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='aimaker.predictor.qlearning.TableRecord.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='aimaker.predictor.qlearning.TableRecord.action', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward', full_name='aimaker.predictor.qlearning.TableRecord.reward', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=297,
)


_QLEARNINGMODEL = _descriptor.Descriptor(
  name='QlearningModel',
  full_name='aimaker.predictor.qlearning.QlearningModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='explore_prob', full_name='aimaker.predictor.qlearning.QlearningModel.explore_prob', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_info', full_name='aimaker.predictor.qlearning.QlearningModel.action_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='table', full_name='aimaker.predictor.qlearning.QlearningModel.table', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=457,
)

_ACTIONINFO.fields_by_name['action_type'].enum_type = _ACTIONTYPE
_QLEARNINGMODEL.fields_by_name['action_info'].message_type = _ACTIONINFO
_QLEARNINGMODEL.fields_by_name['table'].message_type = _TABLERECORD
DESCRIPTOR.message_types_by_name['ActionInfo'] = _ACTIONINFO
DESCRIPTOR.message_types_by_name['TableRecord'] = _TABLERECORD
DESCRIPTOR.message_types_by_name['QlearningModel'] = _QLEARNINGMODEL
DESCRIPTOR.enum_types_by_name['ActionType'] = _ACTIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActionInfo = _reflection.GeneratedProtocolMessageType('ActionInfo', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONINFO,
  '__module__' : 'protocol.QLearning_pb2'
  # @@protoc_insertion_point(class_scope:aimaker.predictor.qlearning.ActionInfo)
  })
_sym_db.RegisterMessage(ActionInfo)

TableRecord = _reflection.GeneratedProtocolMessageType('TableRecord', (_message.Message,), {
  'DESCRIPTOR' : _TABLERECORD,
  '__module__' : 'protocol.QLearning_pb2'
  # @@protoc_insertion_point(class_scope:aimaker.predictor.qlearning.TableRecord)
  })
_sym_db.RegisterMessage(TableRecord)

QlearningModel = _reflection.GeneratedProtocolMessageType('QlearningModel', (_message.Message,), {
  'DESCRIPTOR' : _QLEARNINGMODEL,
  '__module__' : 'protocol.QLearning_pb2'
  # @@protoc_insertion_point(class_scope:aimaker.predictor.qlearning.QlearningModel)
  })
_sym_db.RegisterMessage(QlearningModel)


# @@protoc_insertion_point(module_scope)
